# -*- coding: utf-8 -*-

$LOAD_PATH << File.dirname(File.expand_path(__FILE__)) if RUBY_VERSION >= "1.9.0"
require "pupil/essentials"
require "pupil/base"
require "pupil/schemes"
require "pupil/general"
require "pupil/account"
require "pupil/statuses"
require "pupil/users"
require "pupil/direct_messages"
require "pupil/lists"
require "pupil/friendships"
require "pupil/blocks"
require "pupil/search"
require "pupil/help"